# Generated by Django 5.2.7 on 2025-10-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('position', models.CharField()),
                ('salary', models.IntegerField()),
                ('email', models.EmailField(blank=True, default='patirer765@etenx.com', max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField()),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN-PROCESS', 'In-Prodess'), ('COMPLETED', 'completed')], default='Pending')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ImageField(blank=True, default='task_asset/default_img.jpg', null=True, upload_to='task_asset')),
                ('assigne_to', models.CharField(blank=True, default='NAN', null=True)),
                ('priority', models.CharField(choices=[('H', 'H'), ('M', 'M'), ('L', 'L')], default='M', max_length=1)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
